kind: pipeline
name: broker-websocket

steps:
  - name: test
    image: openjdk:8-jdk-alpine
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - chmod +x ./mvnw && ./mvnw clean package 
    when:
      branch:
        - master
        - dev

  - name: docker
    image: plugins/docker
    settings:
      username: macoredroid
      password:
        from_secret: macoredroid
      repo: macoredroid/broker-websocket
      tags:
        - v1.0.0
    when:
      branch:
        - master

volumes:
  - name: maven-cache
    host:
      path: /maven-cache