kind: pipeline
name: broker-gateway

steps:
  - name: test
    image: openjdk:8-jdk-alpine
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - chmod +x ./mvnw  && ./mvnw clean package -Dspring.profiles.active=product
    when:
      branch:
        - master
        - master-*
        - dev
        - fix-*



  - name: docker
    image: plugins/docker
    settings:
      username: zhiyuanma0401
      password:
        from_secret: zhiyuanma0401
      repo: registry.cn-hangzhou.aliyuncs.com/macoredroid/broker-websocket
      registry: registry.cn-hangzhou.aliyuncs.com
      tags:
        - brokertwo
    when:
      branch:
        - master-*

volumes:
  - name: maven-cache
    host:
      path: /maven-cache