kind: pipeline
name: broker-websocket

steps:
  - name: test
    image: openjdk:8-jdk-alpine
    volumes:
      - name: maven-cache
        path: /root/.m2
    commands:
      - sleep 5
      - chmod +x ./mvnw && ./mvnw test -Dspring.profiles.active=droneCI && ./mvnw clean package -Dspring.profiles.active=droneCI
    when:
      branch:
        - master
        - dev


  - name: docker
    image: plugins/docker
    settings:
      username: macoredroid
      password:
        from_secret: dockerhub_secrets
      repo: macoredroid/broker-websocket
      tags:
        - v1.0.0
    when:
      branch:
        - master

