apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-websocket
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: broker-websocket
    spec:
      containers:
      - name: broker-websocket
        image: registry.cn-hangzhou.aliyuncs.com/macoredroid/broker-websocket:v1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

